import { Blinker } from "next/font/google";
import "./globals.css";

const inter = Blinker({
  variable: "blinker",
  subsets: ["latin-ext"],
  weight: ["100", "300", "400", "600", "700", "800", "900"],
});

export const metadata = {
  title: "minimalist e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
